# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_J7DUOLTE_DTS) := \
	exynos7884-j7duolte_swa_00.dtb \
	exynos7884-j7duolte_swa_01.dtb \
	exynos7884-j7duolte_swa_02.dtb \
	exynos7884-j7duolte_swa_03.dtb

dtb-$(CONFIG_JACKPOTLTE_DTS) := \
	exynos7885-jackpotlte_eur_open_03.dtb \
	exynos7885-jackpotlte_eur_open_04.dtb \
	exynos7885-jackpotlte_eur_open_05.dtb \
	exynos7885-jackpotlte_eur_open_06.dtb \
	exynos7885-jackpotlte_eur_open_07.dtb

dtb-$(CONFIG_JACKPOT2LTE_DTS) := \
	exynos7885-jackpot2lte_eur_open_03.dtb \
	exynos7885-jackpot2lte_eur_open_04.dtb \
	exynos7885-jackpot2lte_eur_open_05.dtb \
	exynos7885-jackpot2lte_eur_open_06.dtb \
	exynos7885-jackpot2lte_eur_open_07.dtb

always          := $(dtb-y) $(dtbo-y)

clean-files       := *.dtb*
